[book]
authors = ["Nathan Douglas"]
language = "en"
multilingual = false
src = "src"
title = "GoldenTooth"
description = "A low-level, step-by-step, thoroughly-documented descent into Hell."

[build]
create-missing = true

[output.html]
mathjax-support = true
site-url = "/"
git-repository-url = "https://github.com/goldentooth/blog"
git-repository-icon = "fa-github"
